config/routes.rb
Rails.application.routes.draw do
#  root 'home#index'

  resources :offices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/office.rb
class Office < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
    def index
        @offices = Office.all
    end
    
    def show
        @office = Office.find(params[:id])
        render json: @office
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offices/index.html.erb
<% @offices.each do |office| %>
<div>
  <li>Name: <%= link_to office.name, office_path(office), :data => { :officeId => office.id } %> </li>
  <li>Company: <%= office.company %></li>
  <br>
 </div>
<% end %>


<div id="results"></div>

app/views/offices/show.html.erb
<div>
  <li>Name: <%= @office.name %></li>
  <li>Company: <%= @office.company %></li>
 </div>